# Data source configuration
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        druid:
            # Main database
#            master:
#                url: jdbc:mysql://localhost:3306/MUSEngage?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
#                username: root
#                password: Xbb941122
            master:
                url: jdbc:mysql://musengage.cpgewo428h7c.ap-southeast-1.rds.amazonaws.com:3306/MUSEngage?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
                username: admin
                password: xbb941122
            # Secondary (slave) database
            slave:
                # Slave datasource switch / disabled by default
                enabled: false
                url:
                username:
                password:
            # Initial connection count
            initialSize: 5
            # Minimum number of idle connections in the pool
            minIdle: 10
            # Maximum number of active connections in the pool
            maxActive: 20
            # Maximum wait time to get a connection (ms)
            maxWait: 60000
            # Connection timeout duration (ms)
            connectTimeout: 30000
            # Network socket timeout duration (ms)
            socketTimeout: 60000
            # Interval between eviction checks (ms)
            timeBetweenEvictionRunsMillis: 60000
            # Minimum time a connection can stay idle in the pool (ms)
            minEvictableIdleTimeMillis: 300000
            # Maximum time a connection can stay in the pool (ms)
            maxEvictableIdleTimeMillis: 900000
            # SQL used to validate whether a connection is valid
            validationQuery: SELECT 1 FROM DUAL
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            webStatFilter:
                enabled: true
            statViewServlet:
                enabled: true
                # Whitelist IPs (leave empty to allow all)
                allow:
                url-pattern: /druid/*
                # Console management username and password
                login-username: ruoyi
                login-password: 123456
            filter:
                stat:
                    enabled: true
                    # Record slow SQL
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true
